import { defineConfig } from 'tsdown'

const CLIENT_EXTERNALS = [
  'react',
  'react/jsx-runtime',
  'react-dom',
  'react-dom/client',
  '@deepseek-ai/cordis',
  '@deepseek-ai/dsh-client-ui-primitives',
  '@deepseek-ai/dsh-client-ui-slots',
]

export default defineConfig([
  {
    name: '@senguoyun/dsh-arkme',
    entry: {
      index: 'src/index.ts',
      'plugin-updater-helper': 'src/plugin-updater-helper-cli.ts',
      'persistent-extension': 'src/extensions/persistent-runtime.ts',
      'bundle-runtime': 'src/extensions/bundle-runtime.ts',
      'extension-profile-restart-helper': 'src/extensions/profile-restart-helper.ts',
    },
    outDir: 'lib',
    format: 'esm',
    platform: 'node',
    target: 'es2024',
    fixedExtension: false,
    dts: false,
    clean: false,
    deps: {
      alwaysBundle: [
        '@sentry/node',
        'mediabunny',
        'pinyin-pro',
        'unified',
        'remark-parse',
        'remark-gfm',
        'micromark-util-decode-string',
      ],
    },
  },
  {
    name: '@senguoyun/dsh-arkme/client',
    entry: { client: 'src/client/index.tsx' },
    outDir: 'lib',
    format: 'cjs',
    platform: 'browser',
    // tsdown defaults CJS resolution to Node even for a browser factory.
    // Keep conditional imports (such as vfile's #minproc) on browser entries.
    inputOptions: { platform: 'browser' },
    target: 'es2022',
    fixedExtension: false,
    dts: false,
    clean: false,
    loader: { '.svg': 'base64', '.png': 'base64' },
    sourcemap: true,
    external: CLIENT_EXTERNALS,
    noExternal: (id: string) => CLIENT_EXTERNALS.includes(id) ? undefined : true,
    define: {
      'process.env.NODE_ENV': JSON.stringify(process.env.NODE_ENV ?? 'production'),
    },
    outputOptions: {
      entryFileNames: 'client.js',
      banner: 'window.__ModuleLoader__.load({ id: "@senguoyun/dsh-arkme", factory: (require) => {',
      footer: 'return module.exports; } });',
      intro: 'var module = { exports: {} }; var exports = module.exports;',
    },
  },
  {
    name: '@senguoyun/dsh-arkme/harness-session',
    entry: { 'harness-session-client': 'src/client/harness-session-client.ts' },
    outDir: 'lib', format: 'cjs', platform: 'browser', inputOptions: { platform: 'browser' }, target: 'es2022',
    fixedExtension: false, dts: false, clean: false,
    outputOptions: {
      entryFileNames: 'harness-session-client.js',
      banner: 'window.__ModuleLoader__.load({ id: "@senguoyun/dsh-arkme/harness-session", factory: (require) => {',
      footer: 'return module.exports; } });',
      intro: 'var module = { exports: {} }; var exports = module.exports;',
    },
  },
  {
    name: '@senguoyun/dsh-arkme/harness-onboarding',
    entry: { 'harness-onboarding-client': 'src/client/harness-onboarding-client.tsx' },
    outDir: 'lib', format: 'cjs', platform: 'browser', inputOptions: { platform: 'browser' }, target: 'es2022',
    fixedExtension: false, dts: false, clean: false,
    external: ['react'],
    outputOptions: {
      entryFileNames: 'harness-onboarding-client.js',
      banner: 'window.__ModuleLoader__.load({ id: "@senguoyun/dsh-arkme/harness-onboarding", factory: (require) => {',
      footer: 'return module.exports; } });',
      intro: 'var module = { exports: {} }; var exports = module.exports;',
    },
  },
  {
    name: '@senguoyun/dsh-arkme/harness-model',
    entry: { 'harness-model-client': 'src/client/harness-model-client.tsx' },
    outDir: 'lib', format: 'cjs', platform: 'browser',
    inputOptions: { platform: 'browser' }, target: 'es2022',
    fixedExtension: false, dts: false, clean: false,
    external: CLIENT_EXTERNALS,
    noExternal: (id: string) => CLIENT_EXTERNALS.includes(id) ? undefined : true,
    define: { 'process.env.NODE_ENV': JSON.stringify(process.env.NODE_ENV ?? 'production') },
    outputOptions: {
      entryFileNames: 'harness-model-client.js',
      banner: 'window.__ModuleLoader__.load({ id: "@senguoyun/dsh-arkme/harness-model", factory: (require) => {',
      footer: 'return module.exports; } });',
      intro: 'var module = { exports: {} }; var exports = module.exports;',
    },
  },
  {
    name: '@senguoyun/dsh-arkme/sdk',
    entry: { sdk: 'src/sdk/index.ts' },
    outDir: 'lib',
    format: 'esm',
    platform: 'browser',
    target: 'es2022',
    fixedExtension: false,
    dts: false,
    clean: false,
  },
])
