import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

const source = readFileSync(new URL('../src/client/ArkmeSettingsSurface.tsx', import.meta.url), 'utf8')
const shellSource = readFileSync(new URL('../src/client/ArkmePersistentShell.tsx', import.meta.url), 'utf8')
const navigationSource = readFileSync(new URL('../src/client/ArkmeProductNavigation.tsx', import.meta.url), 'utf8')
const adapterSource = readFileSync(new URL('../src/client/index.tsx', import.meta.url), 'utf8')
const redesignCss = readFileSync(new URL('../src/client/redesign/arkme-redesign.css', import.meta.url), 'utf8')

describe('ArkmeSettingsSurface', () => {
  it('keeps Arkme account and update capabilities in the redesigned settings surface', () => {
    expect(source).toContain("callArkme<ArkmeUserProfileSnapshot>('user.profile'")
    expect(source).toContain("callArkme<ArkmeAuthSnapshot>('auth.logout')")
    expect(source).toContain('退出登录')
    expect(source).toContain('aria-label="Arkme 设置"')
    expect(source).toContain('buildArkmePluginUpdateRow')
    expect(source).toContain('立即更新')
    expect(source).not.toContain('<SettingsRow title="个人资料"')
    expect(source).not.toContain('<SettingsRow title="登录与安全"')
    expect(source).not.toContain('<SettingsRow title="执行前确认"')
    expect(source).not.toContain('<SettingsRow title="可读取内容"')
    expect(source).not.toContain('<SettingsRow title="外观"')
    expect(source).not.toContain('<SettingsRow title="模型与 API Key"')
    expect(source).toContain('ArkmeAppUpdateSnapshot')
    expect(source).toContain('arkmeAppUpdateStore')
    expect(source).toContain("title={appUpdateRow.label}")
    expect(navigationSource).not.toContain('<strong>我的账户</strong>')
    expect(navigationSource).toContain('arkmeUi.openDshSettings()')
  })

  it('clears the previous account projection before loading another authenticated user', () => {
    expect(source).toMatch(/if \(authState\.auth\?\.status !== 'authenticated'\) \{\s*setProfile\(undefined\)\s*setError\(''\)\s*return/)
    expect(source).toMatch(/const controller = new AbortController\(\)\s*setProfile\(undefined\)\s*setError\(''\)\s*void callArkme<ArkmeUserProfileSnapshot>\('user.profile'/)
  })

  it('positions the DSH account section at the top before paint', () => {
    expect(source).toMatch(/useLayoutEffect\(\(\) => \{\s*scrollArkmeSettingsSurface\(surfaceRef\.current\)/)
    expect(source).not.toContain('document.getElementById')
    expect(source).not.toContain('settingsSection')
  })

  it('inherits the native DSH settings canvas without a standalone compatibility mode', () => {
    expect(adapterSource).toContain('<ArkmeSettingsSurface />')
    expect(source).not.toContain('ArkmeSettingsHost')
    expect(source).not.toContain('data-arkme-settings-host')
    expect(redesignCss).toMatch(/\.arkme-redesign-settings-surface \{[^}]*background: transparent;/)
    expect(redesignCss).toMatch(/\.arkme-redesign-settings-group \{[^}]*border-radius: 0;[^}]*background: transparent;/)
    expect(redesignCss).toMatch(/body\[data-ds-dark-theme\] \.arkme-redesign-settings-surface,[\s\S]*?\.arkme-redesign-settings-group \{[^}]*background: transparent !important;/)
  })

  it('leaves DSH as the only scroll owner and prevents row overflow', () => {
    expect(redesignCss).toMatch(/\.arkme-redesign-settings-surface \{[^}]*height: auto;[^}]*overflow: visible;/)
    expect(redesignCss).toMatch(/\.arkme-redesign-setting-row \{[^}]*box-sizing: border-box;/)
    expect(redesignCss).not.toMatch(/\.arkme-redesign-settings-group \{[^}]*overflow: visible;/)
    expect(redesignCss).not.toMatch(/\.arkme-redesign-settings-surface \{[^}]*overflow-[xy]: auto;/)
  })

  it('uses the Demo settings groups and adapts the DSH task conversation layout', () => {
    expect(redesignCss).toContain('.arkme-redesign-settings-group')
    expect(redesignCss).toContain('.arkme-redesign-settings-profile')
    expect(redesignCss).toContain('.arkme-redesign-task-conversation [data-chat-flow]')
    expect(redesignCss).not.toContain('body[data-arkme-task-session]')
    expect(redesignCss).toContain('--dsh-composer-card-max-width: calc(100% - 32px)')
    expect(redesignCss).toContain('--dsh-chat-content-width: calc(100% - 64px)')
    expect(redesignCss).toContain('max-width: none !important')
    expect(redesignCss).toContain('[data-arkme-directory-visible="true"]')
    expect(redesignCss).toContain('[data-arkme-directory-visible="false"]')
    expect(redesignCss).toContain('grid-template-columns: 356px minmax(0, 1fr) 0 !important')
    expect(redesignCss).toContain('grid-template-columns: 72px minmax(0, 1fr) 0 !important')
    expect(redesignCss).toContain('overflow-y: auto')
    expect(redesignCss).toContain('.arkme-redesign-profile-menu button')
    expect(redesignCss).toContain('background: transparent')
    expect(redesignCss).toContain('.arkme-native-desktop [data-arkme-owned="persistent-sidebar"] > [data-arkme-owned="product-navigation"]')
    expect(redesignCss).toContain('padding-top: 28px !important')
    expect(shellSource).toContain("authState.auth.status !== 'authenticated'")
    expect(shellSource).toContain("ui.calendarOpen !== true")
    expect(shellSource).not.toContain("renderSlot('sidebar.settings'")
    expect(adapterSource).toContain('arkmeUi.bindSettingsOpener(openOfficialSettings)')
    expect(adapterSource).toContain("ctx.slots.inject('settings.section'")
    expect(adapterSource).toContain("id: 'arkme-account'")
    expect(adapterSource).toContain("label: '我的账户'")
    expect(adapterSource).toContain('[data-slot="sidebar.settings"] button[aria-haspopup="dialog"]')
    expect(adapterSource).toContain('[data-arkme-owned="persistent-sidebar"]')
    expect(adapterSource).not.toContain("document.querySelector<HTMLButtonElement>('button[aria-haspopup=\"dialog\"]')")
  })
})
