import { readFileSync } from 'node:fs'
import { renderToStaticMarkup } from 'react-dom/server'
import { describe, expect, it } from 'vitest'
import { ArkmeWorkbenchSurface } from '../src/client/ArkmeWorkbenchSurface.js'

const source = readFileSync(new URL('../src/client/ArkmeWorkbenchSurface.tsx', import.meta.url), 'utf8')
const css = readFileSync(new URL('../src/client/redesign/arkme-redesign.css', import.meta.url), 'utf8')

describe('Arkme personal workbench', () => {
  it('keeps the recognizable Obsidian dashboard sections inside an Arkme-owned surface', () => {
    const markup = renderToStaticMarkup(<ArkmeWorkbenchSurface />)

    expect(markup).toContain('data-arkme-owned="workbench-surface"')
    expect(markup).toContain('>工作台<')
    expect(markup).toContain('arkme-workbench-vault-mark')
    expect(markup).toContain('我的资料库')
    expect(markup).toContain('工作台总览')
    expect(markup).toContain('aria-label="我的工作台三级资料栏"')
    expect(markup).toContain('灵感库')
    expect(markup).toContain('素材库')
    expect(markup).toContain('复盘')
    expect(markup).toContain('硬件库')
    expect(source).toContain('我的资料版图')
    expect(markup).toContain('创作驾驶舱')
    expect(markup).toContain('你的创作正在发生')
    expect(markup).toContain('最近二十八天创作热力图')
    expect(markup).toContain('aria-label="每日计划"')
    expect(markup).toContain('写下今天要完成的事')
    expect(markup).toContain('今日随手记录')
    expect(markup).toContain('aria-controls="arkme-daily-plan-history"')
    expect(markup).toContain('情绪共鸣')
    expect(markup).toContain('评论区火花')
    expect(source).toContain('新建分类')
    expect(source).toContain('aria-label={`打开草稿${entry.title}`}')
    expect(source).toContain('aria-modal="true"')
    expect(source).toContain('arkme-entry-reader-content')
    expect(source).toContain('文字排版工具栏')
    expect(source).toContain('复制一层')
    expect(source).toContain('onContextMenu=')
    expect(source).toContain('新建一级分类')
    expect(source).toContain('新建下级分类')
    expect(source).toContain('确认新建分类')
    expect(source).toContain('onMouseDown={(event) => { event.stopPropagation(); beginQuickAdd')
    expect(source).toContain('下级分类和其中资料也会一并删除')
    expect(markup).toContain('工作台小猫')
  })

  it('keeps the private library in client-local storage without routing to search or other surfaces', () => {
    expect(source).toContain('callArkme<ArkmeUserProfileSnapshot>')
    expect(source).toContain('`${STORAGE_SCOPE}.library.v1`')
    expect(source).toContain('`${STORAGE_SCOPE}.categories.v1`')
    expect(source).toContain('`${STORAGE_SCOPE}.experience.v1`')
    expect(source).toContain('`${STORAGE_SCOPE}.hero.v1`')
    expect(source).toContain('`${STORAGE_SCOPE}.category-page-copy.v1`')
    expect(source).toContain('`${STORAGE_SCOPE}.dashboard-copy.v1`')
    expect(source).toContain('`${STORAGE_SCOPE}.daily-plan.v1`')
    expect(source).toContain('arkme.public-workbench')
    expect(source).toContain('IS_PUBLIC_BUILD ? [] : monthSimulationEntries(Date.now())')
    expect(source).toContain('IS_PUBLIC_BUILD ? [] : privateEntriesSeed()')
    expect(source).toContain('IS_PUBLIC_BUILD ? publicCategoriesSeed : privateCategoriesSeed()')
    expect(source).toContain('monthSimulationEntries(Date.now())')
    expect(source).toContain('demo-month-inspiration')
    expect(source).toContain('从灵感到发布的检查清单')
    expect(source).not.toContain('即我产品背景说明')
    expect(source).not.toContain('Arkme 软植入')
    expect(source).toContain('const editableHeroCopy =')
    expect(source).toContain('onBlur={() => setEditingPageCopy(null)}')
    expect(source).toContain('editableHeroCopy("title", "编辑工作台标题"')
    expect(source).toContain('editableHeroCopy("accountNote", "编辑工作台备注"')
    expect(source).toContain('aria-label="编辑当前分类标题"')
    expect(source).toContain('editablePageCopy("heroHint", "编辑当前分类说明")')
    expect(source).toContain('editablePageCopy("heroPath", "编辑当前分类路径")')
    expect(source).toContain('editablePageCopy("captureTitle", "编辑快速新建区标题")')
    expect(source).toContain('editablePageCopy("captureIntro", "编辑快速新建区说明", true)')
    expect(source).toContain('editablePageCopy("libraryTitle", "编辑资料列表标题")')
    expect(source).toContain('editablePageCopy("libraryIntro", "编辑资料列表说明", true)')
    expect(source).toContain('editablePageCopy("mapTitle", "编辑分类总览标题")')
    expect(source).toContain('editablePageCopy("mapIntro", "编辑分类总览说明", true)')
    expect(source).toContain('editablePageCopy("customiseTitle", "编辑新建分类标题")')
    expect(source).toContain('editablePageCopy("customiseIntro", "编辑新建分类说明", true)')
    expect(source).toContain('editablePageCopy("recentTitle", "编辑最近资料标题")')
    expect(source).toContain('editableDashboardCopy("pulseTitle", "编辑创作状态标题")')
    expect(source).toContain('editableDashboardCopy("activityTitle", "编辑创作足迹标题")')
    expect(source).toContain('editableDashboardCopy("activityNote", "编辑创作足迹说明", true)')
    expect(source).toContain('editableDashboardCopy("nextTitle", "编辑下一步标题")')
    expect(source).toContain('editableDashboardCopy("mapTitle", "编辑资源库分布标题")')
    expect(source).toContain('editableDashboardCopy("recentTitle", "编辑最近更新标题")')
    expect(source).toContain('editableDashboardCopy("overviewTitle", "编辑资料版图标题")')
    expect(source).toContain('editableDashboardCopy("managerTitle", "编辑分类管理标题")')
    expect(source).toContain('editableDashboardCopy("emptyTitle", "编辑空分类标题")')
    expect(source).toContain('editableDashboardCopy("catNote", "编辑小猫提示语")')
    expect(source).toContain('aria-label={`${ariaLabel}，点击修改`}')
    expect(source).toContain('onBlur: () => setEditingPageCopy(null)')
    expect(source).toContain('localStorage.setItem(ENTRY_KEY')
    expect(source).toContain('localStorage.setItem(CATEGORY_KEY')
    expect(source).toContain('localStorage.setItem(DAILY_PLAN_KEY')
    expect(source).toContain('completed: !entry.completed')
    expect(source).toContain('items: plan.items.filter')
    expect(source).toContain('setInterval(() => setNow(new Date()), 30000)')
    expect(source).toContain('aria-label="每日计划历史记录"')
    expect(source).toContain('aria-label={`编辑历史待办：${item.text}`}')
    expect(source).toContain('editingHistoryPlanItemId === item.id')
    expect(source).toContain('onBlur={() => setEditingHistoryPlanItemId(null)}')
    expect(source).toContain('aria-label={`修改${visiblePlanDate}的随手记`}')
    expect(source).toContain('今天写下的待办或随手记，会在这里按日期保存。')
    expect(source).toContain('kind: "inspiration"')
    expect(source).not.toContain('arkmeUi.showSearch')
    expect(source).not.toContain('arkmeUi.showRecordings')
    expect(source).not.toContain('arkmeUi.showCalendar')
    expect(source).not.toContain('2026 / 07 / 08')
  })

  it('keeps cross-library cockpit content exclusive to the workbench overview', () => {
    expect(source).toContain('{!selected && experience === "preview" ? (')
    expect(source).toContain('const selectedEntries = entries')
    expect(source).toContain('below(categories, selected.id).includes(item.categoryId)')
    expect(source).toContain('{selectedEntries.slice(0, 4).map((entry) => (')
  })

  it('has responsive and reduced-motion visual contracts', () => {
    expect(css).toContain('@media (max-width: 620px)')
    expect(css).toContain('@media (prefers-reduced-motion: reduce)')
    expect(css).toContain('.arkme-workbench-cat')
    expect(css).toContain('.arkme-entry-reader-backdrop')
    expect(css).toContain('.arkme-entry-toolbar')
    expect(css).toContain('.arkme-category-context-menu')
    expect(css).toContain('.arkme-cockpit-summary')
    expect(css).toContain('.arkme-vault-search')
    expect(css).toContain('.arkme-entry-workflow')
    expect(css).toContain('.arkme-page-copy-trigger')
    expect(css).toContain('.arkme-daily-plan-list > div.is-complete')
    expect(css).toContain('.arkme-daily-plan-history')
  })
})
