import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'

describe('group member add UI', () => {
  it('matches the pre-release collaborator list and invite flow', () => {
    const source = readFileSync(join(process.cwd(), 'src/client/ArkmeGroupChatControls.tsx'), 'utf8')
    expect(source).toContain("callArkme<ArkmeGroupMemberCandidateList>('group.member-candidates'")
    expect(source).toContain("callArkme<ArkmeGroupMemberAddResult>('group.members.add'")
    expect(source).toContain('aria-pressed={checked}')
    expect(source).toContain("snapshot?.mode === 'approval_invite' && selected.length > 0 ? '发送邀请'")
    expect(source).toContain('Promise.allSettled')
    expect(source).toContain("callArkme<ArkmeGroupBotCandidateList>('group.bots'")
    expect(source).toContain("callArkme('group.bot.add'")
    expect(source).toContain("type Focus = 'all' | 'group' | 'stranger' | 'bot'")
    expect(source).toContain("未选择对象")
    expect(source).toContain("item.relation === 'contact'")
    expect(source).toContain("item.relation === 'stranger'")
    expect(source).toContain("确认添加")
    expect(source).toContain('添加成员')
    expect(source).toContain('协作者{snapshot === undefined')
    expect(source).toContain('邀请协作者')
    expect(source).toContain('二维码有效期')
    expect(source).toContain("'复制链接'")
    expect(source).toContain("'保存'")
    expect(source).toContain('邀请链接已复制')
    expect(source).toContain("transform: 'translate(-50%, -50%)'")
    expect(source).toContain('setTimeout(() => { setCopied(false) }, 1800)')
    expect(source).toContain('<InviteSavingSpinner />')
    expect(source).toContain('aria-busy={busy || undefined}')
    expect(source).toContain("action('save', '保存', saveQr, qrUrl === '' || saving, saving)")
    expect(source).toContain("callArkme<ArkmeGroupInvitePreview>('group.invite-preview'")
    expect(source).toContain('{member.recordCount}条快记')
  })
})
