import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'

describe('group member add UI', () => {
  it('matches the pre-release collaborator list and invite flow', () => {
    const source = readFileSync(join(process.cwd(), 'src/client/ArkmeGroupChatControls.tsx'), 'utf8')
    expect(source).toContain("callArkme<ArkmeGroupMemberCandidateList>('group.member-candidates'")
    expect(source).toContain("sourceRef: props.source.sourceRef, query: '', limit: 50")
    expect(source).toContain('setSnapshot(undefined)')
    expect(source).toContain('setGroups([])')
    expect(source).toContain("callArkme<ArkmeGroupMemberAddResult>('group.members.add'")
    expect(source).toContain('aria-pressed={checked}')
    expect(source).toContain("type Focus = 'all' | 'group' | 'privateChat' | 'bot'")
    expect(source).toContain('groupSourceRefs: [group.sourceRef]')
    expect(source).toContain('groupSourceRefs: groups.map(group => group.sourceRef)')
    expect(source).toContain('正在加载群成员')
    expect(source).toContain('暂无可选群成员')
    expect(source).toContain('没有找到相关对象')
    expect(source).toContain("label: '陌生人'")
    expect(source).toContain("sectionTitle('陌生人')")
    expect(source).toContain('暂无陌生人')
    expect(source).toContain("effectiveFocus === 'all' && visiblePrivateChats.length > 0")
    expect(source).toContain("item.alreadyMember === true")
    expect(source).toContain("const primaryText = snapshot?.mode === 'approval_invite'")
    expect(source).toContain("selectedCount > 0 ? `${primaryText}（${String(selectedCount)}）` : primaryText")
    expect(source).toContain('Promise.allSettled')
    expect(source).toContain("callArkme<ArkmeGroupBotCandidateList>('group.bots'")
    expect(source).toContain("callArkme('group.bot.add'")
    expect(source).toContain("未选择对象")
    expect(source).toContain("item.relation === 'contact'")
    expect(source).toContain("item.relation === 'stranger'")
    expect(source).toContain("确认添加")
    expect(source).toContain('添加成员')
    expect(source).toContain('协作者{visibleSnapshot === undefined')
    expect(source).toContain('邀请协作者')
    expect(source).toContain('二维码有效期')
    expect(source).toContain("'复制链接'")
    expect(source).toContain("'保存'")
    expect(source).toContain('邀请链接已复制')
    expect(source).toContain("transform: 'translate(-50%, -50%)'")
    expect(source).toContain('setTimeout(() => { setCopied(false) }, 1800)')
    expect(source).toContain('<InviteSavingSpinner />')
    expect(source).toContain('aria-busy={busy || undefined}')
    expect(source).toContain("action('save', '保存', saveQr, qrUrl === '' || saving, saving)")
    expect(source).toContain("callArkme<ArkmeGroupInvitePreview>('group.invite-preview'")
    expect(source).toContain('{member.recordCount}条快记')
    expect(source).toContain('drawerScrim')
    expect(source).toContain('onPointerDown={event => { event.preventDefault(); props.onClose() }}')
    expect(source).toContain("window.addEventListener('keydown', dismissOnEscape)")

    const sidebarSource = readFileSync(join(process.cwd(), 'src/client/ArkmeSidebar.tsx'), 'utf8')
    expect(sidebarSource).toContain('member.avatarRef === undefined')
    expect(sidebarSource).toContain('<RobotIcon size={14} weight="fill" />')
  })
})
