import { afterEach, describe, expect, it, vi } from 'vitest'
import { InterwovenReadReceiptStore } from '../src/client/interwoven-read-receipt-store.js'
import type { ArkmeInterwovenReadReceiptList } from '../src/types.js'

afterEach(() => { vi.useRealTimers() })
const unread = (momentId: string) => ({ momentId, reader: 'peer' as const, status: 'unread' as const })

describe('interwoven receipt scheduling', () => {
  it('batches visible rows only, deduplicates rows and never exceeds 20 per request', async () => {
    vi.useFakeTimers()
    const load = vi.fn(async (refs: string[]) => ({ items: refs.map(unread) }))
    const store = new InterwovenReadReceiptStore('private', load)
    const registrations = Array.from({ length: 46 }, (_, i) => store.register(String(i), String(i)))
    registrations.slice(0, 45).forEach(registration => registration.setVisible(true))
    store.register('0', '0').setVisible(true)
    await vi.advanceTimersByTimeAsync(100)
    expect(load.mock.calls.map(([refs]) => refs.length)).toEqual([20, 20, 5])
    expect(store.get('45')).toBeUndefined()
    store.dispose()
  })
  it('refreshes unread rows, stops polling read rows, and responds to invalidation', async () => {
    vi.useFakeTimers()
    const load = vi.fn(async () => ({ items: [unread('a')] }))
    const store = new InterwovenReadReceiptStore('private', load)
    store.register('a', 'ref').setVisible(true)
    await vi.advanceTimersByTimeAsync(100)
    expect(store.get('ref')?.status).toBe('unread')
    load.mockResolvedValue({ items: [{ ...unread('a'), status: 'read' as any }] })
    await vi.advanceTimersByTimeAsync(15000)
    expect(store.get('ref')?.status).toBe('read')
    await vi.advanceTimersByTimeAsync(90000)
    expect(load).toHaveBeenCalledTimes(2)
    store.refresh()
    await vi.advanceTimersByTimeAsync(100)
    expect(load).toHaveBeenCalledTimes(3)
    store.dispose()
  })
  it('cancels hidden/inactive views and prevents late account results from restoring state', async () => {
    vi.useFakeTimers()
    let finish!: (result: ArkmeInterwovenReadReceiptList) => void
    const load = vi.fn((_refs: string[], _signal: AbortSignal) => new Promise<ArkmeInterwovenReadReceiptList>(resolve => { finish = resolve }))
    const store = new InterwovenReadReceiptStore('private', load)
    store.register('a', 'a').setVisible(true)
    await vi.advanceTimersByTimeAsync(100)
    store.setForeground(false)
    expect(load.mock.calls[0]![1].aborted).toBe(true)
    finish({ items: [unread('a')] })
    await vi.advanceTimersByTimeAsync(90000)
    expect(store.get('a')).toBeUndefined()
    expect(load).toHaveBeenCalledOnce()
    store.setForeground(true)
    await vi.advanceTimersByTimeAsync(0)
    store.dispose()
    finish({ items: [unread('a')] })
    await vi.advanceTimersByTimeAsync(100)
    expect(store.get('a')).toBeUndefined()
  })
  it('does not keep a stale unread after failures and recovers with bounded backoff', async () => {
    vi.useFakeTimers()
    const load = vi.fn(async () => ({ items: [unread('a')] }))
    const store = new InterwovenReadReceiptStore('private', load)
    const row = store.register('a', 'a'); row.setVisible(true)
    await vi.advanceTimersByTimeAsync(100)
    load.mockRejectedValueOnce(new Error('offline'))
    store.refresh()
    await vi.advanceTimersByTimeAsync(100)
    expect(store.get('a')).toBeUndefined()
    await vi.advanceTimersByTimeAsync(30000)
    expect(store.get('a')?.status).toBe('unread')
    row.dispose()
    await vi.advanceTimersByTimeAsync(60000)
    expect(load).toHaveBeenCalledTimes(3)
    store.dispose()
  })
  it('ignores mismatched and duplicate result identities', async () => {
    vi.useFakeTimers()
    const load = vi.fn(async () => ({ items: [unread('other')] }))
    const store = new InterwovenReadReceiptStore('private', load)
    store.register('a', 'ref').setVisible(true)
    await vi.advanceTimersByTimeAsync(100)
    expect(store.get('ref')).toBeUndefined()
    load.mockResolvedValue({ items: [unread('a'), unread('a')] })
    store.refresh(); await vi.advanceTimersByTimeAsync(100)
    expect(store.get('ref')).toBeUndefined()
    store.dispose()
  })
})
