import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { ArkmeMessagePreparingReporter } from '../src/client/message-preparing-reporter.js'

const first = { accountScope: 'prod:1', sourceKey: 'one', sourceRef: 'ref-one' }
const second = { ...first, sourceKey: 'two', sourceRef: 'ref-two' }
const flush = async () => { await vi.advanceTimersByTimeAsync(0) }
function setup() {
  const transport = { report: vi.fn(async () => {}), cancel: vi.fn(async () => {}) }
  const reporter = new ArkmeMessagePreparingReporter(transport)
  reporter.setTarget(first)
  reporter.setFocused(true)
  return { reporter, transport }
}
beforeEach(() => { vi.useFakeTimers(); vi.setSystemTime(100_000) })
afterEach(() => { vi.useRealTimers() })

describe('message preparing reporter', () => {
  it('does not renew cleared input when an overdue heartbeat runs before the empty timer', async () => {
    const { reporter, transport } = setup()
    reporter.input('a'); await vi.advanceTimersByTimeAsync(600)
    await vi.advanceTimersByTimeAsync(2700)
    reporter.input('ab'); await vi.advanceTimersByTimeAsync(100)
    reporter.input('')
    vi.setSystemTime(103_800)
    await vi.advanceTimersByTimeAsync(200)
    expect(transport.report).toHaveBeenCalledOnce()
    expect(transport.cancel).toHaveBeenCalledOnce()
    reporter.dispose()
  })
  it('does not let repeated empty editor events extend the first empty deadline', async () => {
    const { reporter, transport } = setup()
    reporter.input('a'); await vi.advanceTimersByTimeAsync(600)
    reporter.input(''); await vi.advanceTimersByTimeAsync(200)
    reporter.input(''); await vi.advanceTimersByTimeAsync(100)
    expect(transport.cancel).toHaveBeenCalledOnce()
    reporter.dispose()
  })
  it('drops a cleared pending intent when a prior request settles before its overdue empty timer', async () => {
    const { reporter, transport } = setup()
    let finish!: () => void
    transport.report.mockImplementationOnce(() => new Promise<void>(resolve => { finish = resolve }))
    reporter.input('a'); await vi.advanceTimersByTimeAsync(600)
    reporter.setTarget(second); reporter.input('b'); await vi.advanceTimersByTimeAsync(600)
    reporter.input('')
    vi.setSystemTime(101_600)
    finish(); await flush()
    expect(transport.report).toHaveBeenCalledOnce()
    expect(transport.cancel).toHaveBeenCalledOnce()
    reporter.dispose()
  })
  it('does not publish an expired arm callback when a suspended event loop resumes', async () => {
    const { reporter, transport } = setup()
    reporter.input('old input')
    vi.setSystemTime(110_000)
    await vi.advanceTimersByTimeAsync(600)
    expect(transport.report).not.toHaveBeenCalled()
    expect(vi.getTimerCount()).toBe(0)
    reporter.dispose()
  })
  it('drops expired pending intent when a request settles before overdue idle callbacks', async () => {
    const { reporter, transport } = setup()
    let finish!: () => void
    transport.report.mockImplementationOnce(() => new Promise<void>(resolve => { finish = resolve }))
    reporter.input('a'); await vi.advanceTimersByTimeAsync(600)
    reporter.setTarget(second); reporter.input('b'); await vi.advanceTimersByTimeAsync(600)
    vi.setSystemTime(110_000)
    finish(); await flush()
    expect(transport.report).toHaveBeenCalledOnce()
    expect(transport.cancel).toHaveBeenCalledOnce()
    reporter.dispose()
  })
  it('arms only after meaningful user input and renews without per-keystroke HTTP', async () => {
    const { reporter, transport } = setup()
    await vi.advanceTimersByTimeAsync(1000)
    expect(transport.report).not.toHaveBeenCalled()
    reporter.input('hello')
    await vi.advanceTimersByTimeAsync(599)
    expect(transport.report).not.toHaveBeenCalled()
    await vi.advanceTimersByTimeAsync(1)
    expect(transport.report).toHaveBeenCalledTimes(1)
    expect(transport.report.mock.calls[0]?.[0]).toEqual(first)
    reporter.input('hello world')
    await vi.advanceTimersByTimeAsync(3000)
    expect(transport.report).toHaveBeenCalledTimes(2)
    reporter.dispose()
  })
  it('ignores empty text and unfocused input; stops idle input after five seconds', async () => {
    const { reporter, transport } = setup()
    reporter.input('  ')
    await vi.advanceTimersByTimeAsync(600)
    expect(transport.report).not.toHaveBeenCalled()
    reporter.setFocused(false)
    reporter.input('draft')
    await vi.advanceTimersByTimeAsync(600)
    expect(transport.report).not.toHaveBeenCalled()
    reporter.setFocused(true)
    reporter.input('live')
    await vi.advanceTimersByTimeAsync(5000)
    expect(transport.cancel).toHaveBeenCalledTimes(1)
    reporter.dispose()
  })
  it('allows a 300ms empty grace and arms again after deleting before activation', async () => {
    const { reporter, transport } = setup()
    reporter.input('a'); await vi.advanceTimersByTimeAsync(100)
    reporter.input(''); await vi.advanceTimersByTimeAsync(600)
    expect(transport.report).not.toHaveBeenCalled()
    reporter.input('b'); await vi.advanceTimersByTimeAsync(600)
    expect(transport.report).toHaveBeenCalledTimes(1)
    reporter.input(''); await vi.advanceTimersByTimeAsync(299)
    expect(transport.cancel).not.toHaveBeenCalled()
    reporter.input('c'); await vi.advanceTimersByTimeAsync(1)
    expect(transport.cancel).not.toHaveBeenCalled()
    reporter.input(''); await vi.advanceTimersByTimeAsync(300)
    expect(transport.cancel).toHaveBeenCalledTimes(1)
    reporter.dispose()
  })
  it.each(['stop', 'blur', 'dispose', 'switch', 'rotate', 'logout'])(
    'cancels the captured old target on %s and never reports restored drafts', async action => {
      const { reporter, transport } = setup()
      reporter.input('hello'); await vi.advanceTimersByTimeAsync(600)
      if (action === 'stop') reporter.stop()
      if (action === 'blur') reporter.setFocused(false)
      if (action === 'dispose') reporter.dispose()
      if (action === 'switch') reporter.setTarget(second)
      if (action === 'rotate') reporter.setTarget({ ...first, sourceRef: 'rotated' })
      if (action === 'logout') reporter.setTarget(undefined)
      await flush()
      expect(transport.cancel).toHaveBeenCalledTimes(1)
      expect(transport.cancel.mock.calls[0]?.[0]).toEqual(first)
      await vi.advanceTimersByTimeAsync(6000)
      expect(transport.report).toHaveBeenCalledTimes(1)
      reporter.dispose()
    },
  )
  it('serializes a late report, old cancellation, and new target without a queue of heartbeats', async () => {
    const { reporter, transport } = setup()
    let finish!: () => void
    transport.report.mockImplementationOnce(() => new Promise<void>(resolve => { finish = resolve }))
    reporter.input('a'); await vi.advanceTimersByTimeAsync(600)
    reporter.setTarget(second); reporter.input('b')
    await vi.advanceTimersByTimeAsync(600)
    expect(transport.report).toHaveBeenCalledTimes(1)
    expect(transport.cancel).not.toHaveBeenCalled()
    finish(); await flush()
    expect(transport.cancel.mock.calls[0]?.[0]).toEqual(first)
    expect(transport.report.mock.calls[1]?.[0]).toEqual(second)
    expect(transport.cancel.mock.invocationCallOrder[0]).toBeLessThan(transport.report.mock.invocationCallOrder[1]!)
    reporter.dispose()
  })
  it('cancels after an in-flight report completes even when disposed', async () => {
    const { reporter, transport } = setup()
    let finish!: () => void
    transport.report.mockImplementationOnce(() => new Promise<void>(resolve => { finish = resolve }))
    reporter.input('a'); await vi.advanceTimersByTimeAsync(600)
    reporter.dispose(); finish(); await flush()
    expect(transport.cancel).toHaveBeenCalledOnce()
    reporter.input('b'); reporter.setFocused(true)
    await vi.advanceTimersByTimeAsync(10_000)
    expect(transport.report).toHaveBeenCalledOnce()
  })
  it('dispatches a renewed capability report with a version newer than its delayed old cancellation', async () => {
    const { reporter, transport } = setup()
    let finish!: () => void
    transport.report.mockImplementationOnce(() => new Promise<void>(resolve => { finish = resolve }))
    reporter.input('a'); await vi.advanceTimersByTimeAsync(600)
    reporter.setTarget({ ...first, sourceRef: 'rotated' }); reporter.input('b')
    await vi.advanceTimersByTimeAsync(600)
    finish(); await flush()
    expect(transport.report.mock.calls[1]![1]).toBeGreaterThan(transport.cancel.mock.calls[0]![1]!)
    reporter.dispose()
  })
  it('absorbs failures, backs off repeated reports, and keeps cancellation independent', async () => {
    const { reporter, transport } = setup()
    transport.report.mockRejectedValue(new Error('offline'))
    reporter.input('a'); await vi.advanceTimersByTimeAsync(600)
    for (let i = 0; i < 4; i++) { reporter.input(`a${i}`); await vi.advanceTimersByTimeAsync(3000) }
    expect(transport.report).toHaveBeenCalledTimes(3)
    reporter.stop(); await flush()
    expect(transport.cancel).toHaveBeenCalledOnce()
    reporter.dispose()
  })
})
