import { afterEach, describe, expect, it, vi } from 'vitest'
import { watchPrivateInteractionDirectory } from '../src/client/use-private-interaction-directory.js'
import type { ArkmePrivateInteractionDirectoryPage, ArkmeSourceItem } from '../src/types.js'

const row = (key: string): ArkmeSourceItem => ({ sourceKey: key, sourceRef: key, kind: 'private_chat', displayName: key, activeAtMillis: 1, unreadCount: 0 })
const page = (key: string, more = false): ArkmePrivateInteractionDirectoryPage => ({
  contractVersion: 1, sourceScope: 'chat_group_mentions', scopeComplete: true, uncoveredSources: [],
  version: 'a'.repeat(64), items: [row(key)], hasMore: more, ...(more ? { nextCursor: 'next' } : {}),
})
const stops: (() => void)[] = []
afterEach(() => { stops.splice(0).forEach(stop => stop()); vi.useRealTimers() })
function start(read: Parameters<typeof watchPrivateInteractionDirectory>[0]['read']) {
  let invalidate!: () => void
  const publish = vi.fn()
  const watcher = watchPrivateInteractionDirectory({ read, publish, subscribe: listener => { invalidate = listener; return vi.fn() } })
  stops.push(() => watcher.dispose())
  return { publish, invalidate, stop: () => watcher.dispose(), retry: () => watcher.retry() }
}
describe('private interaction directory refresh', () => {
  it('publishes recent contacts before the remaining pages finish', async () => {
    const older = Promise.withResolvers<ArkmePrivateInteractionDirectoryPage>()
    const read = vi.fn().mockResolvedValueOnce(page('recent', true)).mockReturnValueOnce(older.promise)
    const { publish } = start(read)
    await vi.waitFor(() => expect(read).toHaveBeenCalledTimes(2))
    expect(publish).toHaveBeenLastCalledWith([row('recent')])
    expect(read.mock.calls[1]?.slice(0, 2)).toEqual(['next', 'a'.repeat(64)])
    older.resolve(page('older'))
    await vi.waitFor(() => expect(publish).toHaveBeenLastCalledWith([row('recent'), row('older')]))
  })
  it('coalesces invalidations without aborting in-flight work and discards its stale response', async () => {
    vi.useFakeTimers()
    const first = Promise.withResolvers<ArkmePrivateInteractionDirectoryPage>()
    const read = vi.fn().mockReturnValueOnce(first.promise).mockResolvedValue(page('latest'))
    const { publish, invalidate } = start(read)
    invalidate(); invalidate(); invalidate()
    expect(read.mock.calls[0]?.[2].aborted).toBe(false)
    first.resolve(page('stale'))
    await vi.advanceTimersByTimeAsync(151)
    expect(read).toHaveBeenCalledTimes(2)
    expect(publish).toHaveBeenCalledTimes(1)
    expect(publish).toHaveBeenLastCalledWith([row('latest')])
  })
  it('clears an obsolete projection on permission/read failure and supports retry', async () => {
    vi.useFakeTimers()
    const read = vi.fn().mockResolvedValueOnce(page('peer')).mockRejectedValueOnce(new Error('403')).mockResolvedValue(page('peer'))
    const { publish, invalidate } = start(read)
    await vi.advanceTimersByTimeAsync(1)
    invalidate(); await vi.advanceTimersByTimeAsync(151)
    expect(publish).toHaveBeenLastCalledWith([], expect.any(String))
    invalidate(); await vi.advanceTimersByTimeAsync(151)
    expect(publish).toHaveBeenLastCalledWith([row('peer')])
  })
  it('drops late account responses and cancels the transport on disposal', async () => {
    const pending = Promise.withResolvers<ArkmePrivateInteractionDirectoryPage>()
    const read = vi.fn().mockReturnValue(pending.promise)
    const { publish, stop } = start(read)
    stop(); pending.resolve(page('old-account'))
    await Promise.resolve()
    expect(read.mock.calls[0]?.[2].aborted).toBe(true)
    expect(publish).not.toHaveBeenCalled()
  })
  it('restarts version conflicts from page one, but bounds repeated failures', async () => {
    vi.useFakeTimers()
    const read = vi.fn().mockRejectedValue(new Error('interaction-version-changed'))
    const { publish } = start(read)
    await vi.advanceTimersByTimeAsync(1000)
    expect(read).toHaveBeenCalledTimes(2)
    expect(read.mock.calls.every(call => call[0] === undefined && call[1] === undefined)).toBe(true)
    expect(publish).toHaveBeenLastCalledWith([], expect.any(String))
  })

  it('revalidates recent contacts after repeated older-page conflicts instead of rolling them back', async () => {
    vi.useFakeTimers()
    const read = vi.fn()
      .mockResolvedValueOnce(page('old', true)).mockRejectedValueOnce(new Error('version_changed'))
      .mockResolvedValueOnce(page('old', true)).mockRejectedValueOnce(new Error('version_changed'))
      .mockResolvedValueOnce(page('fresh', true))
    const { publish } = start(read)
    await vi.advanceTimersByTimeAsync(1000)
    expect(read).toHaveBeenCalledTimes(5)
    expect(read.mock.calls[4]?.slice(0, 2)).toEqual([undefined, undefined])
    expect(publish).toHaveBeenLastCalledWith([row('fresh')], '较早群互动暂未加载，点击重试')
  })

  it('does not retain earlier-page content if fresh permission revalidation fails', async () => {
    vi.useFakeTimers()
    const read = vi.fn()
      .mockResolvedValueOnce(page('old', true)).mockRejectedValueOnce(new Error('version_changed'))
      .mockResolvedValueOnce(page('old', true)).mockRejectedValueOnce(new Error('version_changed'))
      .mockRejectedValueOnce(new Error('403'))
    const { publish } = start(read)
    await vi.advanceTimersByTimeAsync(1000)
    expect(publish).toHaveBeenLastCalledWith([], '群互动同步暂未完成，点击重试')
  })

  it('replaces background reads for explicit retry and ignores a late old completion', async () => {
    vi.useFakeTimers()
    const old = Promise.withResolvers<ArkmePrivateInteractionDirectoryPage>()
    const current = Promise.withResolvers<ArkmePrivateInteractionDirectoryPage>()
    const read = vi.fn().mockReturnValueOnce(old.promise).mockReturnValueOnce(current.promise).mockResolvedValue(page('after-event'))
    const { publish, retry, invalidate } = start(read)
    retry(); retry()
    expect(read).toHaveBeenCalledTimes(2)
    expect(read.mock.calls[0]?.[2].aborted).toBe(true)
    expect(read.mock.calls[1]?.[3]).toBe('foreground')
    old.resolve(page('obsolete'))
    await vi.advanceTimersByTimeAsync(0)
    invalidate(); invalidate()
    await vi.advanceTimersByTimeAsync(200)
    expect(read).toHaveBeenCalledTimes(2) // The old finally cannot mark the new run idle.
    expect(publish).not.toHaveBeenCalled()
    current.resolve(page('also-obsolete'))
    await vi.advanceTimersByTimeAsync(200)
    expect(read).toHaveBeenCalledTimes(3)
    expect(read.mock.calls[2]?.[3]).toBe('foreground')
    expect(publish).toHaveBeenCalledTimes(1)
    expect(publish).toHaveBeenLastCalledWith([row('after-event')])
    invalidate(); await vi.advanceTimersByTimeAsync(200)
    expect(read.mock.calls[3]?.[3]).toBe('background')
  })

  it('keeps explicit retry priority through pagination, version recovery and permission revalidation', async () => {
    vi.useFakeTimers()
    const read = vi.fn().mockRejectedValueOnce(new Error('offline'))
      .mockResolvedValueOnce(page('old', true)).mockRejectedValueOnce(new Error('version_changed'))
      .mockResolvedValueOnce(page('old', true)).mockRejectedValueOnce(new Error('version_changed'))
      .mockResolvedValueOnce(page('fresh', true))
    const { publish, retry } = start(read)
    await vi.advanceTimersByTimeAsync(0)
    retry()
    await vi.advanceTimersByTimeAsync(1000)
    expect(read).toHaveBeenCalledTimes(6)
    expect(read.mock.calls[0]?.[3]).toBe('background')
    expect(read.mock.calls.slice(1).every(call => call[3] === 'foreground')).toBe(true)
    expect(publish).toHaveBeenLastCalledWith([row('fresh')], '较早群互动暂未加载，点击重试')
  })

  it('cancels a scheduled automatic refresh on retry and cancels the replacement on disposal', async () => {
    vi.useFakeTimers()
    const pending = Promise.withResolvers<ArkmePrivateInteractionDirectoryPage>()
    const read = vi.fn().mockResolvedValueOnce(page('old')).mockReturnValueOnce(pending.promise)
    const { publish, invalidate, retry, stop } = start(read)
    await vi.advanceTimersByTimeAsync(0)
    invalidate(); retry()
    await vi.advanceTimersByTimeAsync(1000)
    expect(read).toHaveBeenCalledTimes(2)
    stop(); retry()
    expect(read.mock.calls[1]?.[2].aborted).toBe(true)
    pending.resolve(page('late'))
    await vi.advanceTimersByTimeAsync(1000)
    expect(publish).toHaveBeenCalledTimes(1)
    expect(read).toHaveBeenCalledTimes(2)
  })
})
