import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

describe('test plugin configuration', () => {
  it('routes each owner API to its test service', () => {
    const patch = readFileSync(new URL('../cordis.patch.yml', import.meta.url), 'utf8')

    expect(patch).toContain('environment: test')
    expect(patch).toContain('authBaseUrl: https://jotmo.senguo.me')
    expect(patch).toContain('subjectBaseUrl: https://jotmo-subject.senguo.me')
    expect(patch).toContain('recordBaseUrl: https://jotmo-record.senguo.me')
    expect(patch).toContain('chatBaseUrl: https://jotmo-chat.senguo.me')
    expect(patch).toContain('imBaseUrl: https://jotmo-im.senguo.me')
    expect(patch).toContain('webrtcBaseUrl: https://jotmo-webrtc.senguo.me')
    expect(patch).toContain('worldBaseUrl: https://jotmo-world.senguo.me')
    expect(patch).toContain('relationBaseUrl: https://jotmo-relation.senguo.me')
    expect(patch).toContain('intelligentBaseUrl: https://jotmo-intelligent.senguo.me')
    expect(patch).toContain('audioBaseUrl: https://jotmo-audio.senguo.me')
    expect(patch).toContain('extensionPublishBaseUrl: https://jotmo-extension-publish.senguo.me')
    expect(patch).toContain('test-ed25519-20260819-1')
    expect(patch).toContain('toolProfile: business')
    expect(patch).toContain('relatedRecordingsEnabled: true')
    expect(patch).not.toContain('relatedRecordingSharingEnabled:')
    expect(patch).toContain('interwovenMomentsEnabled: true')
    expect(patch).toContain('richMediaRenderEnabled: true')
    expect(patch).toContain('richMediaSendEnabled: true')
    expect(patch).toContain('maxUploadBytes: 104857600')
    expect(patch).toContain('allowProduction: false')
    expect(patch).toContain('updateCheckEnabled: true')
    expect(patch).toContain('updateChannel: stable')
    expect(patch).toContain('updateRegistryUrl: https://registry.npmjs.org')
    expect(patch).toContain('updateCheckIntervalHours: 12')
    expect(patch).toContain('updateAllowLocalInstall: false')
    expect(patch).not.toContain('chatBaseUrl: https://im.jotmo.cc')
  })
})
