const jotmoEmojiUnicodeById: Readonly<Record<string, string>> = {
  angry_face: '😡',
  awkward_face: '😐',
  heart_eyes: '😍',
  smiling_face: '😊',
  squint_tongue: '😝',
  yelling_face: '😣',
  sweat_smile: '😅',
  grinning_face: '😁',
  side_eye_smirk: '😏',
  joy_face: '😂',
  unamused_face: '🙄',
  disappointed_face: '😔',
  surprised_face: '😮',
  teary_face: '😢',
  annoyed_face: '😒',
  kiss_heart: '😘',
  yummy_face: '😋',
  goofy_grin: '🤪',
  shouting_face: '😫',
  speechless_sweat: '😓',
  cute_face: '🥹',
  relaxed_face: '😌',
  wink_tongue: '😜',
  nauseated_face: '🤢',
  sleeping_face: '😴',
  sleepy_face: '😪',
  groggy_face: '😩',
  crying_face: '😭',
  disgusted_face: '😖',
  shocked_face: '😱',
  star_struck_face: '🤩',
  yawning_face: '🥱',
  sobbing_face: '😭',
  frustrated_face: '😣',
  excited_face: '😛',
  sick_face: '😨',
  worried_face: '😟',
  kiss_sweat_face: '😗',
  speechless_face: '😑',
  masked_face: '😷',
  stunned_face: '😳',
  green_shock_face: '🤢',
  silent_face: '😶',
  yawn_face: '🥱',
  pleading_face: '🥺',
  dizzy_face: '😵',
  red_angry_face: '😠',
  queasy_face: '🤮',
  ok_hand: '👌',
  thumb_up: '👍',
  thanks_hands: '🙏',
  fist: '👊',
  handshake: '🤝',
  thumb_down: '👎',
  victory_hand: '✌️',
  fist_salute: '🙏',
}

const jotmoEmojiTokenPattern = /\[(?:jm_emoji|im_emoji):([a-z0-9_]+)\]/gu

/** Mirrors Jotmo mobile's plain-text fallback: known tokens render as emoji and unknown tokens remain intact. */
export function jotmoEmojiPlainText(value: string): string {
  if (value === '' || !value.includes('_emoji:')) return value
  return value.replace(jotmoEmojiTokenPattern, (token, emojiId: string) => jotmoEmojiUnicodeById[emojiId] ?? token)
}
